name: Continuous Integration / Continuous Deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  pull:
    name: Pulling the code
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3  
  build:
    name: Setup env secrets, build and restarting the project
    needs: [pull]
    runs-on: self-hosted
    steps:
    - name: Set up PostgreSQL environment variables
      run: echo "\nspring.datasource.password=${{ secrets.DB_PASSWORD }}" >> FootballStats/FootballStats/src/main/resources/application-ovh.properties
    - name: cleaning package
      run: cd FootballStats/FootballStats && mvn clean package
    - name: restarting service
      run: sudo systemctl restart footballapi.service
