name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  pull:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3  
  build:
    needs: [pull]
    runs-on: self-hosted
    steps:
    - name: cleaning package
      run: cd FootballStats/FootballStats && mvn clean package
    - name: restarting service
      run: sudo systemctl restart footballapi.service
